#' Calculate the EAP for a Rasch model
#' 
#' Calculates the expected a posteriori value of an ability parameter (theta) by
#' integrating over a user-specified domain of values along the posterior function 
#' generated by a \code{Rasch} object.
#' 
#' @param raschObj An object of class \code{Rasch}
#' @param lower The lower limit of integration (default to -6)
#' @param upper The upper limit of integration (default to 6)
#' 
#' @return A list with one element
#'  \item{theta}{The value of theta}
#'  
#'  @author Ryden W. Butler: \email{r.butler@@wustl.edu}
#'  @examples 
#'  
#'  exRasch <- new('Rasch', name = 'Me', a = 0, y = 1)
#'  eap(exRasch)
#'  @seealso likelihood, prior
#'  @rdname eap
#'  @aliases eap,ANY-method
#'  @export
setGeneric(name = 'eap',
           def = function(raschObj, lower = -6, upper = 6) {
             standardGeneric('eap')
           }
           )
#' @export
setMethod(f = 'eap',
          definition = function(raschObj, lower = -6, upper = 6) {
            VectorLikelihood <- Vectorize(likelihood, 'theta', SIMPLIFY = F)
            posterior <- function(theta) {
              return(unlist(VectorLikelihood(raschObj, theta))*prior(theta)$pi)
            }
            return(integrate(f = posterior, lower = lower, upper = upper))
          }
          )